image:
  file: .gitpod.Dockerfile

tasks:
  - name: Get kubeconfig from DO
    command: |
      doctl auth init --access-token $DO_API_KEY
      doctl kubernetes cluster kubeconfig save $DO_CLUSTER_ID
      gp sync-done kubeconfig
  - name: Launch DevSpace
    command: |
      gp sync-await kubeconfig
      devspace dev